rest_api_homepage:
    path:     /
    defaults: { _controller: RestApiBundle:Default:index }
    
list_products:
    path:     product/list
    defaults: { _controller: RestApiBundle:RestProduct:getAllProducts }
    methods:  [GET]
    
list_product_by_category:
    path:     product/category/{id}
    defaults: { _controller: RestApiBundle:RestProduct:getProductByCategory }
    methods:  [GET]
    requirements:
        id: \d+
   
add_product:
    path:     product/add
    defaults: { _controller: RestApiBundle:RestProduct:addProduct }
    methods:  [POST]
    
add_category:
    path:     category/add
    defaults: { _controller: RestApiBundle:RestCategory:addCategory }
    methods:  [POST]
    
edit_category:
    path:     category/edit/{id}
    defaults: { _controller: RestApiBundle:RestCategory:editCategory }
    methods:  [GET|POST]
    requirements:
        id: \d+
        
list_categories:
    path:     category/list
    defaults: { _controller: RestApiBundle:RestCategory:getAllCategory }
    methods:  [GET]

category:
    path:     category/{$id}
    defaults: { _controller: RestApiBundle:RestCategory:getCategory }
    methods:  [GET]
    requirements:
        id: \d+

    
